[project]
name = "visualizacion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "polars>=1.30.0",
    "ruff>=0.11.12",
]
